#!/bin/bash

# TODO: import this from one place
VERSION="0.0.1"
PACKAGE="brokerchunks-api"
COMPANY="brokerchunks"

ENTRY_PORT=8080
CONATINER_PORT=8080
EXTERNAL_IP="192.168.0.90"

docker run -p ${ENTRY_PORT}:${CONATINER_PORT} ${COMPANY}/${PACKAGE}:${VERSION}